apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-loader
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - pods
      - events
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-loader
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: openshift-loader
subjects:
  - kind: ServiceAccount
    namespace: openshift-loader
    name: openshift-loader

