apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-graceful
  name: graceful-test
  labels:
    graceful-test: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      graceful-test: "true"
  template:
    metadata:
      name: graceful-test
      labels:
        graceful-test: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      hostNetwork: true
      serviceAccountName: graceful-test
      securityContext:
        runAsUser: 0
      containers:
        - name: graceful-test
          image: docker.io/tohinkashem/graceful:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command:
            - /usr/bin/graceful-termination
            - -metrics-port=9090
            - -v=4
            - -kubelet-kubeconfig=/var/lib/kubelet/kubeconfig
            - -kube-apiserver-pod-name=kube-apiserver-$(MY_NODE_NAME)
            - -concurrent=25
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/kubelet
            name: kubeconfig
          env:
          # - name: GODEBUG
          #   value: http2debug=2
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
      - name: kubeconfig
        hostPath:
          path: /var/lib/kubelet
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
