apiVersion: v1
kind: Service
metadata:
  name: graceful-test
  namespace: openshift-graceful
  labels:
    graceful-test: "true"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    graceful-test: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graceful-test-metrics
  namespace: openshift-graceful
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graceful-test-metrics
  namespace: openshift-graceful
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: graceful-test-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: graceful-test-metrics
  namespace: openshift-graceful
  labels:
    graceful-test: "true"
spec:
  endpoints:
  - interval: 5s
    port: metrics
  namespaceSelector:
    matchNames:
    - openshift-graceful
  selector:
    matchLabels:
      graceful-test: "true"
