apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graceful-test
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: graceful-test
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: graceful-test
subjects:
  - kind: ServiceAccount
    namespace: openshift-graceful
    name: graceful-test

