apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graceful-test-scc-use
  namespace: openshift-graceful
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - hostnetwork
      - hostaccess
      - privileged
      - anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graceful-test-scc-use
  namespace: openshift-graceful
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: graceful-test-scc-use
subjects:
  - kind: ServiceAccount
    namespace: openshift-graceful
    name: graceful-test
